// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdTg3MIARRw672ZGjCY_pi9hj7ZapJM8',
    appId: '1:715160013269:web:41b752b8408818b587955c',
    messagingSenderId: '715160013269',
    projectId: 'app-gestionsupportdecours',
    authDomain: 'app-gestionsupportdecours.firebaseapp.com',
    storageBucket: 'app-gestionsupportdecours.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHS4uYKR8MK-PKXewynnqaET4cVCHOL8',
    appId: '1:715160013269:android:a73e73a98bf9ce7d87955c',
    messagingSenderId: '715160013269',
    projectId: 'app-gestionsupportdecours',
    storageBucket: 'app-gestionsupportdecours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZcvw3rK0057P07H_YcmwYt1drYW9hFGA',
    appId: '1:715160013269:ios:b8b2a7184b4e8fa887955c',
    messagingSenderId: '715160013269',
    projectId: 'app-gestionsupportdecours',
    storageBucket: 'app-gestionsupportdecours.firebasestorage.app',
    iosClientId: '715160013269-lvpgfuv215157m31h9eqecgres9bggat.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGestionsupportdecours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZcvw3rK0057P07H_YcmwYt1drYW9hFGA',
    appId: '1:715160013269:ios:b8b2a7184b4e8fa887955c',
    messagingSenderId: '715160013269',
    projectId: 'app-gestionsupportdecours',
    storageBucket: 'app-gestionsupportdecours.firebasestorage.app',
    iosClientId: '715160013269-lvpgfuv215157m31h9eqecgres9bggat.apps.googleusercontent.com',
    iosBundleId: 'com.example.appGestionsupportdecours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcdTg3MIARRw672ZGjCY_pi9hj7ZapJM8',
    appId: '1:715160013269:web:8f6550c0ff64ec5587955c',
    messagingSenderId: '715160013269',
    projectId: 'app-gestionsupportdecours',
    authDomain: 'app-gestionsupportdecours.firebaseapp.com',
    storageBucket: 'app-gestionsupportdecours.firebasestorage.app',
  );
}
