// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdOXx5sXymysVRR-Llxp1K6hBkK3plJIg',
    appId: '1:1038934382764:web:db53f7ba880659298ba709',
    messagingSenderId: '1038934382764',
    projectId: 'doc-rd-isi',
    authDomain: 'doc-rd-isi.firebaseapp.com',
    storageBucket: 'doc-rd-isi.firebasestorage.app',
    measurementId: 'G-R2T0CXPG8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZlvM8tzmwRPKf_ut-3p8XMxgDCq0gndY',
    appId: '1:1038934382764:android:c18eb4f37073e28d8ba709',
    messagingSenderId: '1038934382764',
    projectId: 'doc-rd-isi',
    storageBucket: 'doc-rd-isi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy4Le432W2TCfhU-uCMyD9bWBcgFP3XW0',
    appId: '1:1038934382764:ios:0aa78bcce3497b868ba709',
    messagingSenderId: '1038934382764',
    projectId: 'doc-rd-isi',
    storageBucket: 'doc-rd-isi.firebasestorage.app',
    iosBundleId: 'com.example.appGestionsupportdecours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy4Le432W2TCfhU-uCMyD9bWBcgFP3XW0',
    appId: '1:1038934382764:ios:0aa78bcce3497b868ba709',
    messagingSenderId: '1038934382764',
    projectId: 'doc-rd-isi',
    storageBucket: 'doc-rd-isi.firebasestorage.app',
    iosBundleId: 'com.example.appGestionsupportdecours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdOXx5sXymysVRR-Llxp1K6hBkK3plJIg',
    appId: '1:1038934382764:web:c50dcaa995f684828ba709',
    messagingSenderId: '1038934382764',
    projectId: 'doc-rd-isi',
    authDomain: 'doc-rd-isi.firebaseapp.com',
    storageBucket: 'doc-rd-isi.firebasestorage.app',
    measurementId: 'G-957XESMSZY',
  );
}